
1.宏包加载
```{r}
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(car)
library(afex)
library(gridExtra)
library(grid)
library(ggsignif)
```

2.加载数据（行为实验2）
```{r}
coherence2 <- read_xlsx("F:/桌面文件夹/近红外论文/影像学数据/coherence(DLPFC)_2.xlsx")
coherence5 <- read_xlsx("F:/桌面文件夹/近红外论文/影像学数据/coherence(DLPFC)_5.xlsx")

```

3.1 coherence2
```{r}
data_coherence2 = data.frame(coherence2$`stim-frequence`, coherence2$`coherence-pre`,coherence2$`coherence-ing`,coherence2$`coherence-post`) 
# 更名
names(data_coherence2) <- c("stim.frequence","pre-stimulation","stimulating",'post-stimulation')

data_coherence2 <- pivot_longer(data = data_coherence2, cols = c("pre-stimulation","stimulating",'post-stimulation'), names_to = "stim_state", values_to = "coherence")

data_coherence2$stim.frequence <- as.factor(data_coherence2$stim.frequence)
data_coherence2$stim_state <- factor(data_coherence2$stim_state ,levels = c("pre-stimulation","stimulating",'post-stimulation'))

data_coherence2_summary <- data_coherence2 %>%
  group_by(stim.frequence, stim_state) %>%
  summarise(mean_score = mean(coherence),
            sem_score = sd(coherence) / sqrt(n()))

plot2 <- ggplot(data_coherence2_summary, aes(x = stim_state, y = mean_score, group = stim.frequence, color = stim.frequence)) + 
  geom_line(size = 1, position = position_dodge(width = 0.5)) +
  geom_point(data = data_coherence2, aes(x = stim_state, y = coherence, fill = stim.frequence), 
             position = position_dodge(width = 0.5), shape = 21, fill = "white", size = 3) + 
  geom_errorbar(aes(ymin = mean_score - 3*sem_score, ymax = mean_score + 3*sem_score), width = 0.2, 
                position = position_dodge(width = 0.5), linetype = 1, size = 0.5) + # 细化误差线
  labs(x = "Stimulation State", y = "FC based on coherence") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 12, face = "bold"), # 加粗图例标题
        legend.text = element_text(size = 12),
        legend.key.width = unit(1.5, "line"), # 增加图例间距
        legend.spacing.x = unit(0.5, 'cm'), # 图例项之间间距
        axis.title = element_text(size = 12, face = "bold"), # 加粗坐标轴标题
        axis.text.x = element_text( size=12,hjust = 1)) + 
  theme(panel.grid.major = element_line(color = "gray", linetype = "dotted", size = 0.25), # 细化主网格线
        panel.grid.minor = element_blank())+ scale_color_manual(values = c("#F8766D", "#619CFF"))+  scale_y_continuous(limits = c(0.5, 2.5))

plot2

```
"#619CFF", "#F8766D", "#00BA38"

```{r}
setwd("F:/桌面文件夹/近红外论文/图片")
ggsave("coherence2.jpg", plot2, width = 6, height = 4, units = "in", dpi = 300)
```
3.5 coherence5
```{r}
data_coherence5 = data.frame(coherence5$`stim-frequence`, coherence5$`coherence-pre`,coherence5$`coherence-ing`,coherence5$`coherence-post`) 
# 更名
names(data_coherence5) <- c("stim.frequence","pre-stimulation","stimulating",'post-stimulation')

data_coherence5 <- pivot_longer(data = data_coherence5, cols = c("pre-stimulation","stimulating",'post-stimulation'), names_to = "stim_state", values_to = "coherence")

data_coherence5$stim.frequence <- as.factor(data_coherence5$stim.frequence)
data_coherence5$stim_state <- factor(data_coherence5$stim_state ,levels = c("pre-stimulation","stimulating",'post-stimulation'))

data_coherence5_summary <- data_coherence5 %>%
  group_by(stim.frequence, stim_state) %>%
  summarise(mean_score = mean(coherence),
            sem_score = sd(coherence) / sqrt(n()))

plot5 <- ggplot(data_coherence5_summary, aes(x = stim_state, y = mean_score, group = stim.frequence, color = stim.frequence)) + 
  geom_line(size = 1, position = position_dodge(width = 0.5)) +
  geom_point(data = data_coherence5, aes(x = stim_state, y = coherence, fill = stim.frequence), 
             position = position_dodge(width = 0.5), shape = 21, fill = "white", size = 3) + 
  geom_errorbar(aes(ymin = mean_score - 3*sem_score, ymax = mean_score + 3*sem_score), width = 0.2, 
                position = position_dodge(width = 0.5), linetype = 1, size = 0.5) + # 细化误差线
  labs(x = "Stimulation State", y = "FC based on coherence") +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.title = element_text(size = 12, face = "bold"), # 加粗图例标题
        legend.text = element_text(size = 12),
        legend.key.width = unit(1.5, "line"), # 增加图例间距
        legend.spacing.x = unit(0.5, 'cm'), # 图例项之间间距
        axis.title = element_text(size = 12, face = "bold"), # 加粗坐标轴标题
        axis.text.x = element_text( size=12,hjust = 1)) + 
  theme(panel.grid.major = element_line(color = "gray", linetype = "dotted", size = 0.25), # 细化主网格线
        panel.grid.minor = element_blank())+ scale_color_manual(values = c("#00BA38", "#619CFF"))+  scale_y_continuous(limits = c(0.5, 2.5))

plot5

```
```{r}
setwd("F:/桌面文件夹/近红外论文/图片")
ggsave("coherence5.jpg", plot5, width = 6, height = 4, units = "in", dpi = 300)
```

